feat: add github username to contributor
PreMiD/Schemas pull request #101
Opened 2022-08-13 00:22 UTC by EncryptedDev

Adds `github` to `author` and `contributors`

2022-08-13 00:23 UTC, Timeraa approved these changes

2022-08-13 00:26 UTC, Bas950 requested changes
Will check the rest tomorrow on pc

2022-08-13 00:26 UTC, Bas950 commented on schemas/metadata/1.8.json
> +	"$id": "https://schemas.premid.app/metadata/1.7",
.8

2022-08-13 07:28 UTC, Bas950 commented on schemas/metadata/1.8.json
> +                }
please fix the spacing, and do we still need `name`

2022-08-13 07:28 UTC, Bas950 commented on schemas/metadata/1.8.json
> +			"required": ["name", "id"]
probs good to make it required.

2022-08-13 08:19 UTC, EncryptedDev commented on schemas/metadata/1.8.json
> +                }
Probably best to keep it until the website‘s next major version because we still depend on it on the store afaik

2022-08-13 08:21 UTC, EncryptedDev commented on schemas/metadata/1.8.json
> +			"required": ["name", "id"]
I think if we did, SV would fail constantly because the majority of contributors haven’t added their GH

2022-08-13 10:08 UTC, Bas950 commented on schemas/metadata/1.8.json
> +			"required": ["name", "id"]
But we can just add it for them right? I never added my GH but you added all my presences?

2022-08-13 10:29 UTC, EncryptedDev commented on schemas/metadata/1.8.json
> +			"required": ["name", "id"]
We would have to do that for every ~400 contributors to the repo which isn’t really possible. We just used MS to add staff & popular contributors.

2022-08-14 07:44 UTC, Bas950 commented on schemas/metadata/1.8.json
> +			"required": ["name", "id"]
and don't think its worth it to have it if it isn't required. :/

2022-09-16 20:05 UTC, closed without merging