feat(1.8): minLength 1
PreMiD/Schemas pull request #107
Opened 2022-09-12 16:32 UTC by Bas950

2022-09-12 16:34 UTC, EncryptedDev commented
What's the change?

2022-09-12 19:14 UTC, Bas950 commented
> What's the change? 

minLength 1

2023-06-02 15:10 UTC, theusaf requested changes

2023-06-02 15:10 UTC, theusaf commented on schemas/metadata/1.8.json
> +		},
With the recent asset changes on the Presences repository, these need to be updated to include recodive cdn urls

2023-06-02 15:31 UTC, closed without merging